language: python 
node_js:
  - "8"
python:
  - "3.6"
before_script:
  - export COVERAGE_TOKEN=$COVERAGE_TOKEN
  - export COVERALLS_REPO_TOKEN=$COVERAGE_TOKEN
  - export AIRTABLE_API_KEY=$AIRTABLE_API_KEY
  - export AIRTABLE_BASE_KEY=$AIRTABLE_BASE_KEY
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export REGION=$REGION
  - echo "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  - echo "[default]\nregion = $REGION" >> ~/.aws/config 
install:
  - npm install
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - cp ./bot/config.sample.py ./bot/config.py
script:
  - npm run test
after_success:
  - npm run write-coveralls
  - COVERALLS_REPO_TOKEN=$COVERAGE_TOKEN coveralls
